### ISSUE TITLE
TODO?!

### ISSUE THREAD

**Issue by x-spert** [tehciolo/bookrack#28]
- [x] remove autcomplete
- [x] change current video icon into one more suggestive
- [x] failed to load resource - favicon
- [x] left and right arrows are cropped on mobile and at not-wide screen resolutions 
- [x] add book contents page
- [x] book-deutsch-i-vol2 - pg20 - painter exercise
- [x] update picker exercise in order to control picker size
- [x] update typer exercise by adding confirm picture in some cases
- [x] update painter exercise by adding custom colors for stroke
- [x] section.main-menu goes over triggers even if it is closed so you can't hit the trigger from that aria

**Comment by tehciolo** [comment]
@x-spert
Collaborator
x-spert commented 6 hours ago

- [ ] change current video icon into one more suggestive
- [ ] close button on exercise help panel ?!
- [ ] add loader on ajax start, when page is changed and another one (image) is displayed (downloaded)
- [ ] add option/functionality to move exercise trigger position on horizontal not only on vertical (is good to have especially when we have two exercises in one; ex: ger1, vol2, p49, ex.1)
- [ ] failed to load resource - favicon
- [ ] left and right arrows are cropped on mobile and at not-wide screen resolutions

**Comment by tehciolo** [comment]
Pentru iconita video trebuie modificat si in fiecare carte in siteData.js

**Done**

**Comment by tehciolo** [comment]
Pentru cuprins trebuie modificat si in fiecare carte

**Done**

**Comment by x-spert** [comment]
Cuprins: Daca am un exemplu cu noua implementare, pot sa modific eu.

**Comment by tehciolo** [comment]
Oricum trec prin fiecare carte acum, modific eu.

Am pus exemplu in README la bookrack 

cc @x-spert

**Comment by tehciolo** [comment]
Trebuie modificate si numele cartilor

**Done**
